### PR TITLE
Patch Z-Order Android Problem

### LINKED ISSUE #286: subview doesn't work for me
### Steps to reproduce
1. use the code from master.
2. copy the test code from readme.
3. test on genymotion android emulator run on mac os.
### Expected behaviour

See the capture button
### Actual behaviour

Can't see the capture button
### Environment
- **Node.js version**: 6.1.0
- **React Native version**: 0.25
- **React Native platform + platform version**: Android 5.0
### react-native-camera

**Version**: master

### PR DESCRIPTION
**Pull request by gchiocchio**
Fix #286 issue

### CODE REVIEW

**Comment by rt2zz** [comment]
Looking at the solution a little more, I am not sure I understand. Why does removing and readding the viewfinder solve this bug? this seems a bit risky, and afaict other projects like [maps](https://github.com/lelandrichardson/react-native-maps) do not do this.

Maybe someone with more android experience can weight in..

**Comment by pfeiffer** [comment]
According to [this](http://stackoverflow.com/a/19872801) removing the view, then adding it a z order 0 ensures that it's the backmost view in the view hierarchy.

**Comment by sharynneazhar** [comment]
Is this going to be merged in sometime soon? 😝

**Comment by charpeni** [comment]
@sharynneazhar We're evaluating this solution.

@gchiocchio Can you remove commit 5dc23988899c48a5b65142198654fc1d36fb48ca from your pull request?

**Comment by rt2zz** [comment]
I cherry picked the commit in question and added some comments for future reference 👍  Thanks @gchiocchio

**Pull request closed without merging**
