### PR TITLE
added a way to customize photo and video quality in iOS

### PR DESCRIPTION
**Pull request by manask88**
Added a new option to be able to set up the video/picture quality

### CODE REVIEW

**Comment by rt2zz** [comment]
Awesome :+1: we have a parallel pr on the Android side that we will need to reconcile.

**Comment by manask88** [comment]
Hey @lwansbrough   any news on this?

**Comment by manask88** [comment]
I think @rt2zz  are refering to https://github.com/lwansbrough/react-native-camera/pull/203, right?  which one will you take as the standard API for the quality change? Is there anything I can do to get this moving?

**Comment by danlopez** [comment]
This would be really useful for me as well.

**Comment by elaygl** [comment]
+1

**Comment by realjamie** [comment]
+1

**Comment by rt2zz** [comment]
Does this work only for video. From the code it looks like it should apply to photographs as well...

@lwansbrough how do you feel about this api? Namely the `captureQuality` prop. If you like it I can work on getting android in line with the same api and we can merge this.

**Comment by manask88** [comment]
yup @rt2zz  you are right, this works for both video and pics. I just updated the title so that people dont get confused

**Comment by pjcabrera** [comment]
Any progress on this? It would be great to have this merged.

**Comment by lwansbrough** [comment]
Cool, I would very much like to see this integrated with the solution for Android. Not sure I can get to it tonight. Someone want to take this on? All the work appears to be done - it just requires aligning the APIs between this PR and @juggleru's here: https://github.com/lwansbrough/react-native-camera/pull/203

**Pull request closed without merging**
