### PR TITLE
QR code support for android by using zxing library

### PR DESCRIPTION
**Pull request by carck**
Please review and see if you can merge it.

### CODE REVIEW

**Comment by miletbaker** [comment]
Awesome, great work @carck it will be fantastic if react-native-camera supports QR code scanning on Android. I look forward to this being merged in.

**Comment by rt2zz** [comment]
@carck this looks great and clean implementation. Can you make it the barcode scan in `onPreviewFrame` conditional on having onBarCodeRead defined that way we do not incur the performance cost when not in use?

**Comment by carck** [comment]
@rt2zz I am not familiar with ios, but it seems that barcode scan on ios is not conditional  too.  just to be consist with ios. we need to change both if we want to.

**Comment by rt2zz** [comment]
@carck afaik iOS automatically scans barcodes and we do not have the option to turn it off.

What I am suggesting would be transparent to the consumer since it would only turn off when there was no handler and no changes to the API would be required.

**Comment by baspellis** [comment]
@carck once a barcode is found it seems it stops scanning for other barcodes. This is different than the iOS implementation, where the onBarCodeRead event keeps being fired. Could this be fixed to be in line with iOS?

**Comment by jdeniau** [comment]
@baspellis I got the same bug with [this library](https://github.com/ideacreation/react-native-barcodescanner) and a Nexus 5, but it's working on other phones.

Do you think the problem may come from https://github.com/zxing/zxing ?

**Comment by ahstro** [comment]
First off, awesome that you're working on this! Thank you! However, I decided to try your code, and ran into two distinct problems.


##### 1. I couldn't scan codes.
I'm not sure if I might've just been doing something wrong, but my impression was that this should work if I added a `onBarCodeRead`-prop to my Camera?


##### 2. `doInBackground` causes a crash whenever I switch away from my app, specifically when I Android's the `Last app`-functionality.
Here's the logcat for when that happens:
```
04-03 11:35:57.782 25619 25883 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
04-03 11:35:57.782 25619 25883 E AndroidRuntime: Process: com.gourmand, PID: 25619
04-03 11:35:57.782 25619 25883 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:org.twelf.cmtheme, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
04-03 11:35:57.782 25619 25883 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:309)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
04-03 11:35:57.782 25619 25883 E AndroidRuntime: Caused by: java.lang.RuntimeException: Camera is being used after Camera.release() was called
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at android.hardware.Camera.setHasPreviewCallback(Native Method)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:840)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onResult(RCTCameraViewFinder.java:156)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at com.lwansbrough.RCTCamera.BarcodeReader$ReaderAsyncTask.doInBackground(BarcodeReader.java:62)
04-03 11:35:57.782__ 25619 25883 E AndroidRuntime:        at com.lwansbrough.RCTCamera.BarcodeReader$ReaderAsyncTask.doInBackground(BarcodeReader.java:40)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:295)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-03 11:35:57.782 25619 25883 E AndroidRuntime:        ... 4 more
```

**Comment by kunxi** [comment]
@ahstro: 

This patch only support QR code, which is hard-coded in the constructor. I successfully get the QR code read, but no other UPC codes. 
Since the barcode recognition in the iOS is not configurable, I propose to support all formats zxing supports. 

Also, this plugin will schedule an asynctask for barcode recognition for each frame preview in a fire and forget way.  IMHO, I think a more appropriate way is to track the async task, then:
- in the `onFramePreview` method,  cancel the existing async task before spawning a new one
- in the `stop` method, cancel the async task.

**Comment by ahstro** [comment]
I tried scanning a QR code as well, but didn't have any luck with those either, although I only tried once. Regardless, I agree that it makes more sense to enable all supported formats.

**Comment by codyhazelwood** [comment]
It would be great to see this merged.  There's still some improvements to be made, but it's working well for me (scanning QR codes in both iOS and Android).

**Comment by RealOrangeOne** [comment]
Notice this thread's gone a bit stale. Any idea when this'll be fixed / merged?

**Comment by codyhazelwood** [comment]
I forked carck's fork and updated it to work with RN 0.26.2, and I'm using it in production on iOS and Android with no issues.  QR code scanning is the only thing that I use the library for.

**Comment by anton6** [comment]
@codyhazelwood Thanks for the fork. 

I get a small error: 
```
TypeError: /home/ant/work/mealwheel-business/node_modules/react-native-camera/Camera.js: Duplicate declaration "React"
>   1 | import React, {Component, PropTypes} from 'react';
> > 2 | import React, {
>     |        ^
>   3 |   NativeAppEventEmitter,
>   4 |   DeviceEventEmitter,
>   5 |   Platform,
>     at File.buildCodeFrameError (/home/ant/work/mealwheel-business/node_modules/react-native/node_modules/babel-core/lib/transformation/file/index.js:467:15)
```

But it's easily fixed. Apart from that seems to work nicely.

**Comment by codyhazelwood** [comment]
@anton6 Sorry about that.  Should be fixed now.

**Comment by RealOrangeOne** [comment]
Can confirm working on android nicely! Only problem is it doesnt like to scan multiple images. Once it's scanned an image, it returns it just fine, but then won't scan any others. Any idea why this is happening? If I navigate to another view and back without resetting the app, then i'll scan again.

**Comment by anton6** [comment]
@RealOrangeOne as a work around to that issue I force re-render react-native-camera component after every onBarCodeRead . Not sure if there is a better way to temporarily solve this.

**Comment by kevinnguy** [comment]
Any way to enable other barcode formats? Been hacking around but haven't gotten the camera to scan other than QR codes.

**Comment by kocyigityunus** [comment]
Why is this pull request still waiting?

**Comment by ahstro** [comment]
@kocyigityunus I'm hoping because of [my comment](https://github.com/lwansbrough/react-native-camera/pull/229#issuecomment-204926130) about it not working is a factor, but I'm not sure.

**Comment by M1chaelTran** [comment]
this ticket should be closed as this PR https://github.com/lwansbrough/react-native-camera/pull/413 been merged!

**Comment by ptomasroos** [comment]
This PR is no longer needed since of #413 
Thanks for the efforts

**Pull request closed without merging**
