### PR TITLE
Add alias for photo

### PR DESCRIPTION
**Pull request by browniefed**

### CODE REVIEW

**Comment by rt2zz** [comment]
awesome. Any chance you can implement corresponding functionality on the android side?

Is AVCaptureSessionPresetPhoto better quality than AVCaptureSessionPresetHigh? If so we can just map 'photo' -> 'high' in android.

**Comment by rpopovici** [comment]
@rt2zz Yes, AVCaptureSessionPresetPhoto is better quality

**Comment by browniefed** [comment]
Yep. Taken from the ObjC Code

```
/*!
 @constant AVCaptureSessionPresetPhoto
 @abstract
    An AVCaptureSession preset suitable for high resolution photo quality output.
 
 @discussion
    Clients may set an AVCaptureSession instance's sessionPreset to AVCaptureSessionPresetPhoto
    for full resolution photo quality output.
*/
AVF_EXPORT NSString *const AVCaptureSessionPresetPhoto NS_AVAILABLE(10_7, 4_0) __TVOS_PROHIBITED;

/*!
 @constant AVCaptureSessionPresetHigh
 @abstract
    An AVCaptureSession preset suitable for high quality video and audio output.
 
 @discussion
    Clients may set an AVCaptureSession instance's sessionPreset to AVCaptureSessionPresetHigh
    to achieve high quality video and audio output.  AVCaptureSessionPresetHigh is the
    default sessionPreset value.
*/
AVF_EXPORT NSString *const AVCaptureSessionPresetHigh NS_AVAILABLE(10_7, 4_0) __TVOS_PROHIBITED;

```
High is for both audio and video, photo appears to be just for photo of course.

**Comment by browniefed** [comment]
I also don't know if there is anything equivalent on Android

**Comment by browniefed** [comment]
I assume adding 
```
        private Map<String, Object> getCaptureQualityConstants() {
                return Collections.unmodifiableMap(new HashMap<String, Object>() {
                    {
                        put("low", "low");
                        put("medium", "medium");
                        put("high", "high");
                        put("photo","high");
                    }
                });
            }

```
Would be enough to map `photo` to `high` on android?

**Comment by rt2zz** [comment]
@browniefed exactly that would be perfect

**Comment by browniefed** [comment]
Doneso.

**Comment by rt2zz** [comment]
👍

**Pull request merged**
