### PR TITLE
V1 orientation

### PR DESCRIPTION
**Pull request by rt2zz**
this is a rebased version of https://github.com/lwansbrough/react-native-camera/pull/232 compliments of @rpopovici

I am inclined to take it in but I hesitate due to the large scale of the changes. @corbt can you weigh in on this?

### CODE REVIEW

**Comment by corbt** [comment]
Right now if I understand this right it activates unconditionally. I don't think it should activate if the user has explicitly set an orientation.

On the other hand, the documentation for `orientation` says:

> The orientation property allows you to specify the current orientation of the phone to ensure the viewfinder is "the right way up."

So maybe orientation is only related to the viewfinder, and this is unrelated?

**Comment by rpopovici** [comment]
@rt2zz this is OK, but I don't think is ready for merging because is not taking in consideration the orientation parameter. I am using the real device orientation all the time, and I think this should apply only to auto mode. Beside this @corbt did some changes to add support for video on iOS. I am not seeing these changes here.

**Comment by corbt** [comment]
For what it's worth, I'm using this PR in my own fork right now with support for video on iOS as well.

**Comment by rt2zz** [comment]
got it, closing for now then we can continue discussion in 232

**Pull request closed without merging**
