### PR TITLE
Android support.

### PR DESCRIPTION
**Pull request by farmisen**
Working: 
* set aspect, 
* select camera type, 
* set flash/torch mode,
* take picture and save it to the file system, mediaroll or as data.

Not working: 
* video capture, 
* set orientation.

Known problems: 
* front camera pictures are not oriented correctly.

Tested on:
* Nexus 5 (Android 6.0.1, Marshmallow)
* Genymotion emulator (Android 6.0.1, Marshmallow)

### CODE REVIEW

**Comment by zackify** [comment]
So exciting! I'm going to test this out tomorrow. Thanks for all the work!

**Comment by lwansbrough** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by ippa** [comment]
Amazing work!

**Comment by mattiamanzati** [comment]
👏

**Comment by zackify** [comment]
Can we get some instructions on the readme? Or am I missing something

**Comment by farmisen** [comment]
on it.

**Comment by zackify** [comment]
Thanks!

**Comment by farmisen** [comment]
https://github.com/lwansbrough/react-native-camera/pull/161

**Comment by lwansbrough** [comment]
Just wanted to extend my gratitude again to @farmisen and everyone who has been involved with the Android development thus far. Really great work. There's still a ways to go to feature parity but we're on our way now, so thank you.

I'm going to have to set aside some time to do feature testing as it's been a while since there's been a new version on npm - but that issue is on my radar.

Cheers guys!

**Comment by dangnelson** [comment]
Would love some confirmation on which version of react-native the instructions support. It seems like they support 0.17, but not 0.18?

**Comment by lwansbrough** [comment]
@dangnelson Curious what makes you say that?

**Comment by dangnelson** [comment]
MainActivity.java seems to work differently in 0.18 than 0.17

There's no reference to ReactInstanceManager.builder() in that file.

https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/package/MainActivity.java

**Comment by dangnelson** [comment]
More specifically, I think a lot of it got moved to ReactActivity.java:

https://github.com/facebook/react-native/commit/935cbb76c02cffd378a8f391c6e7443a3da13adc

**Comment by dangnelson** [comment]
@ardowz and I have been trying to resolve the issue here https://github.com/lwansbrough/react-native-camera/issues/165

**Pull request merged**
