### PR TITLE
fix react native 0.19.0 upgrade bugs for android

### PR DESCRIPTION
**Pull request by rpopovici**

### CODE REVIEW

**Comment by lwansbrough** [comment]
@rpopovici This contains changes that should not be made including returning arrays in the promise response.

**Comment by rpopovici** [comment]
@lwansbrough sorry for this. Don't know exactly how github pull request works. Can't you just cherry pick the relevant commit?

**Comment by rpopovici** [comment]
I guess this can be closed now since it was already merged. Thanks

**Comment by rt2zz** [comment]
@rpopovici :+1:

**Pull request closed without merging**
