### PR TITLE
bind this to _onBarCodeRead proxy

### PR DESCRIPTION
**Pull request by robbevan**
barcode read fails currently because 'this' is undefined

### CODE REVIEW

**Comment by charpeni** [comment]
I think this method should be binded in the constructor.

**Comment by chirag04** [comment]
huh? it's binding correctly using the arrow function. I don't think this change is required

**Comment by robbevan** [comment]
Barcode read definitely *doesn't* work for me, fails with: undefined is not an object (evaluating '_this.props.onBarCodeRead')

**Comment by chirag04** [comment]
what's your babelrc look like?

**Comment by robbevan** [comment]
Ah, looks like passPerPreset was the culprit. Thanks.

**Comment by chirag04** [comment]
if you using passPerPreset then you are def going to be hit by this: https://phabricator.babeljs.io/T7274
you might want to downgrade babel to 6.6

**Pull request closed without merging**
