### PR TITLE
Android tap-to-focus and improved (continuous) auto-focus

### PR DESCRIPTION
**Pull request by abrahambotros**
Tap-to-focus

- On tap, compute focus area around motion event's location, and pass this to the camera parameters
  as the new focus area.
- Adds RCTCameraUtils.java file, so far with only a single function that helps compute the focus area
  from a motion event. This file can serve as a location for utility constants and functions for the
  rest of the app, where such things can be extracted out.

Improved (continuous) auto-focus

- Use FOCUS_MODE_CONTINUOUS_PICTURE/VIDEO when possible to enable continuous auto-focus; fall back to
  FOCUS_MODE_AUTO otherwise, if able.

Other changes

- Update README to specify differences between iOS and Android for focus and zoom functionality.
- Update AndroidManifest with more thorough list of permissions and features.
- Update Example package.json react and react-native dependencies to match root package's package.json.

[EDIT]

- Note that there is no visual feedback provided on Android at the tap-to-focus location in the PR. I've noted this is (still) only available on iOS in the updated README. Once this gets merged, we can see about adding some visual feedback in sometime soon for Android.

### CODE REVIEW

**Comment by scerelli** [comment]
Good Job!

**Comment by DibPuelma** [comment]
How do I make this available? Do I need to wait for the PR to be accepted??

**Comment by scerelli** [comment]
@DibPuelma you can point to his commit inside your `package.json` or just install `react-native-camera` this way: `npm install --save react-native-camera@https://github.com/abrahambotros/react-native-camera.git`  then when they merge the PR you can switch back to main npm package.

**Comment by DibPuelma** [comment]
Thank you @scerelli

**Comment by abrahambotros** [comment]
Thanks @scerelli! And just a small addition to what was mentioned to @DibPuelma above: in the somewhat-common case that an external contributor's PR is made from a branch other than their `master` (in this case, I'm making the PR from a branch in my cloned repo called `android-tap-to-focus-and-continuous-auto-focus`), you would want to do something like the following to make sure you pull in the changes from the actual PR branch:

Under `"dependencies"` in your `package.json` file, add: `"react-native-camera": "git+https://github.com/abrahambotros/react-native-camera.git#android-tap-to-focus-and-continuous-auto-focus"`. Then run `npm install` or just `npm install react-native-camera` if you want to specify this is the only package you want to install at the moment.

Alternatively, I think you could just tag on `#android-tap-to-focus-and-continuous-auto-focus` to the command @scerelli gave above.

Otherwise, if you don't specify the appropriate branch, you'll end up pulling in either the `master` branch or the latest release, which often can be exactly the same as the upstream repo (this one).

Either way, let me know if you guys get a chance to test this so we get some feedback on this PR thread! Thanks!

**Comment by yosiat** [comment]
Hi,
@abrahambotros Checked this on Android (Galaxy Note 3) and it works great!
Waiting for this PR to get merged.

**Comment by abrahambotros** [comment]
Great, thanks @yosiat!

**Comment by ptomasroos** [comment]
I will review this @abrahambotros Thanks for you PR!

**Comment by scerelli** [comment]
@abrahambotros i was testing your work and i saw that actually the tap to focus / auto focus works pretty well but i don't see any visual feedback. It still need to be implemented or it has to be turned on via props?

**Comment by abrahambotros** [comment]
@scerelli, you're right, there is no visual feedback implemented here. I noted this in the updated README in this PR, but should have noted this in my commit message as well at the top here (edited now to include that).

Going forward, I think it's probably best to get this PR merged first, especially if anyone suggests any (code) changes. Afterwards, we can see about adding visual feedback for Android, as I agree that this should definitely come soon!

**Comment by scerelli** [comment]
@abrahambotros I implemented it client side using PanGesture so I don't think it will be hard to bring my implementation inside react-native-camera. At least we will have a coherent visual style between the two platforms that is even easy to customise

**Comment by kevinnguy** [comment]
@abrahambotros I've been testing your pull request for a few days and it's been excellent! There are some times where I'll get the error:
`Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference`

I've been trying to reproduce the bug consistently but failed. Do you or anyone knows why this happens sporadically?

**Comment by scerelli** [comment]
@kevinnguy basically i've experienced this error too while i was trying to implement focus and zoom by myself. Basically you get this when you try to access `getParameters()` but camera is null. Camera becomes null when you have a `RuntimeException`.

**Comment by abrahambotros** [comment]
@kevinnguy and @scerelli, thanks for the additional input. If possible, can you run with a debugger or full logs and try to get the line number for this error? I've never encountered it myself even under extensive use, and my code changes in this PR don't actually touch any `getParameters()` calls, so this might be an edge case and a problem in master instead of this PR, but happy to help if we can pinpoint this to something from my changes!

**Comment by kevinnguy** [comment]
@abrahambotros yeah, I think this is a general Android problem that should be addressed in master. Thanks for the great work!

**Comment by jarredszabadi** [comment]
When do we expect this to be merged?

**Comment by ThaJay** [comment]
@ptomasroos good to merge?

**Comment by akotlov** [comment]
@abrahambotros Thank you for implementing the functionality!
Tested on Nexus 5,Nexus 6 and Nexus 6P.  (RN 0.42.0).
One suggestion.
From the source: 
/**
+     * Handles setting focus to the location of the event.
+     *
+     * Note that this will override the focus mode on the camera to FOCUS_MODE_AUTO if available,
+     * even if this was previously something else (such as FOCUS_MODE_CONTINUOUS_*; see also
+     * {@link #startCamera()}. However, this makes sense - after the user has initiated any
+     * specific focus intent, we shouldn't be refocusing and overriding their request!
**/

Seems like no there is no way to reset "manual focus" to "automatic" after tapping on a screen.(except unmounting "CameraView" and remounting again).

Is it possible to implement a timer (5 sec?) that would put a camera into "automatic focus " mode(I am sorry I am not familiar with specific focus modes-speaking in "laymans" terms) again after a tap on a screen?
Seems like that's what "Google camera app" does and it makes sense from a user perspective.

**Comment by abrahambotros** [comment]
@akotlov, great suggestion, definitely reasonable. I don't quite have time right this moment to add this, assuming this isn't a blocking problem for merging this particular PR as-is. But hopefully this will get fully reviewed/merged soon, and I hopefully can find some time to add in the timer you mentioned soon afterwards. @akotlov, or anyone else, please let me know what you think about putting off the timer mentioned in the above comment for a bit/until after this PR gets merged.

**Comment by akotlov** [comment]
@abrahambotros In my use case -its a video sharing app with Snapchat inspired navigation ,not able to release "manual" focus affects user experience pretty bad.Unmounting/mounting Camera view to reset focus seems like pretty "expensive" operation that produce a significant delay to the flow of the app.So,yeah it would be really good to see the "timer"(or another mechanism) to release focus implemented.Let me know if I can be of any help testing and thank you again for your effort.

**Comment by Disjes** [comment]
Hi, seems great, thanks for the work.
I've defined defaultOnFocusComponent= {true}.
And: onFocusChanged: this.onFocusChanged.bind(this),
Also: onFocusChanged(e){
    console.log('FocusChanged!');
  }

Unfortunately onFocusChanged callback is not fired even though index.js recognize the function, also focus does not seem to be done on tap, am I missing something?

**Comment by akotlov** [comment]
@Disjes makes sure you pointing      
 "react-native-camera": "git+https://github.com/abrahambotros/react-native-camera.git#android-tap-to-focus-and-continuous-auto-focus" 
in your package.json.

My Camera View config:
```javascript
 renderCamera() {
    return (
     <View style={styles.container}>
      <Camera
        ref={(cam) => {
          this.camera = cam;
        }}
        type={this.state.type}
        style={styles.preview}
        aspect={Camera.constants.Aspect.fill}
        captureTarget={Camera.constants.CaptureTarget.disk}
        captureMode={Camera.constants.CaptureMode.video}
      /> 
       {!this.state.isRecording && 
         // camera control elements here ... 
         <View>
          <TouchableHighlight/>
          <TouchableHighlight/>
         <View />
      }
     </View>
   )
 }
```
And check if you have any overlaying Components on top of Camera View that wont let touch events pass to it.

**Comment by Disjes** [comment]
Thanks @akotlov I will try, I've got a question, if it is already Merged on master shouldn't it work with https://github.com/lwansbrough/react-native-camera/ update?

Thanks for your help @akotlov

**Comment by akotlov** [comment]
@Disjes I don't have much experience with github ,but I don't think it has been merged yet,still listed as "Open".
From top of the page:
> abrahambotros
wants to merge 1 commit into lwansbrough:master from abrahambotros:android-tap-to-focus-and-continuous-auto-focus
> 

I might be wrong.

**Comment by ThaJay** [comment]
it has not been merged
@chris-at-translate what do you think?

**Comment by Disjes** [comment]
@akotlov you were right it's not merged yet, I pointed to "git+https://github.com/abrahambotros/react-native-camera.git#android-tap-to-focus-and-continuous-auto-focus" in packages.json and now tap-to-focus is working properly on Android, thanks @akotlov for your help and thanks @abrahambotros for this great functionality.

**Comment by chris-at-translate** [comment]
If your wondering if this PR is merged into master, nope it hasn't. A maintainer needs to authorise this PR for it to be merged. @lwansbrough @ptomasroos @rt2zz Hopefully one of these guys could be able to merger this PR.

**Comment by abrahambotros** [comment]
Thank you very much to @akotlov, @ThaJay, and @chris-at-translate for all your help here! Yep, still waiting to merge. @Disjes, glad to hear things are working for you now!

**Comment by ptomasroos** [comment]
Can you rebase this and I promise to take a look at it. @abrahambotros

**Comment by gijsbotje** [comment]
Works perfectly for android, haven't tested ios yet

**Comment by rt2zz** [comment]
👍 @abrahambotros looks like one merge conflict - if you can resolve I think we are ready to get this in

**Comment by LEEY19** [comment]
@abrahambotros let us know when it has been merged. Awesome job buddy!

**Comment by abrahambotros** [comment]
@ptomasroos, @rt2zz, merge conflicts resolved in https://github.com/lwansbrough/react-native-camera/pull/575/commits/6779a0d284cf5d8666f63911d45cf6a8bc82e9c9. Tested on my device and should be good to merge now, unless you want to wait for additional testing. Also added onFocusChanged default empty callback to Example for easier testing in https://github.com/lwansbrough/react-native-camera/pull/575/commits/59bc94c14decd1c88125a3b2f4635fcc9ecd8fd2.

@gijsbotje, thanks for the testing! Should be no changes to iOS, so no worries on not testing there.

@LEEY19, thanks for the support!

**Comment by abrahambotros** [comment]
Btw, we might want to set more precise React/React-Native version dependencies, as I was getting errors testing the Example app on Android with a fresh RN install (0.43+) based off our existing package.json `>=0.40` semver. Anyone testing/reviewing this with the same conditions might need to explicitly set the RN version.

Anyway, this versioning is non-blocking for this current PR, so I'm offloading that to https://github.com/lwansbrough/react-native-camera/pull/679.

**Comment by abrahambotros** [comment]
@rt2zz, thanks for reviewing and merging https://github.com/lwansbrough/react-native-camera/pull/578. Just resolved the merge conflicts that created, so now this PR should actually be finally good to merge!

**Comment by rt2zz** [comment]
@abrahambotros thank you!

**Comment by jqn** [comment]
Has anyone been able to get tap to focus on android. I have the latest version 0.9.4 and it doesn't seem to do anything.

**Comment by abrahambotros** [comment]
@jqn, this is working for me on Android across a couple different devices in daily production use. A couple people above mentioned it was working for them too. What Android version are you using? And did you ensure you added the required permissions/features to your manifest? See https://developer.android.com/reference/android/hardware/Camera.html - namely, the `camera.autofocus` `feature`.

**Comment by jqn** [comment]
Thanks @abrahambotros, I updated my AndroidManifest.xml and touch to focus is working now. 
The other issue was related to overlaying components on top of Camera View blocking touch events. None of these changes I made are in the Readme so it makes it confusing.

These are the changes I made:

```
### Added to my AndroidManifest.xml
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
```

and made sure there were no overlaying elements blocking tap gestures.

**Comment by abrahambotros** [comment]
@jqn, I'll try to address your different points below:

- Regarding the `AndroidManifest` changes, you're right, these unfortunately aren't in the Readme yet. Maybe you could submit a PR to add this in? Just something suggesting to ensure those lines are in your `AndroidManifest` if you want focus features, etc.

- I'm a bit confused on your use of `pointerEvents='none'`, which basically prevents receiving touch events on the view or any of its children, right? So, in particular, `touchable` wouldn't be able to receive touches in your example, right? Sounds like the opposite of what you want for the child `touchable` object and any of its children.

- As stated in the Readme, there is currently no way to disable pinch-to-zoom from JS. Again, PRs welcome for this, as ideally we would have boolean props to enable/disable tap-to-focus, auto-focus, pinch-to-zoom, etc.

**Comment by jqn** [comment]
Thanks for the comments @abrahambotros. I have a viewfinder on top of the camera that was blocking touchables, hence the use of pointerEvents. I'm still trying to figure out how to best implement it to avoid this sort of issue. I'll get a simple pull request going for the AndroidManifest changes.

**Pull request merged**
