### PR TITLE
Android barcode settypes

### PR DESCRIPTION
**Pull request by fbacker**
An continue to add features on branch https://github.com/lwansbrough/react-native-camera/pull/370

Added possibility to set barcode types. And for performance if showViewFinder={true} is used it only scans a small area.

onBarCodeRead must be added for barcode scanner to work. Else it keeps working as a normal camera.

### CODE REVIEW

**Comment by fbacker** [comment]
new commit with updated readme, updated android barcode set types. Follows the strings in readme. 

Anyone that knows objective-c and can update the ios to work with the same strings would be amazing.

For example data matrix in ios is org.iso.DataMatrix and it was DATA_MATRIX in android.
Now by following the readme it should be datamatrix for both. However someone needs to update xcode project for this. Added todos for where the code should be changed.

**Comment by rt2zz** [comment]
This looks good to me, but I do not have time to test, but if someone can take a look at updating ios would be good to get this merged asap

**Comment by fbacker** [comment]
I've now updated ios as well. Would great if someone else also has some time to test it before a merge?

Now both iOS and Android uses the same barcode strings (e.g. datamatrix, iOS: org.iso.DataMatrix, Android: DATA_MATRIX).
This string is also returned to onBarCodeRead

Updated the docs with these changes.

I also noticed iOS bug type code128 was specified as code138.

**Comment by tonypeng** [comment]
Just installed and I'm getting 1-2 FPS on my Nexus 6P, with `showViewFinder={true}`. Any way to improve performance?

**Comment by fbacker** [comment]
Hmm, strange, will have another look at it. Sure that it's nothing else
that is taking the performance? Running on a Samsung Galaxy S3 with no lag.

**Comment by tonypeng** [comment]
I just have a simple setup with a `DrawerLayoutAndroid` and the camera. I edited your code and moved the `onPreviewFrame` behavior to an AsyncTask and I'm now getting 60 FPS, although I couldn't get very accurate scans with `MultiFormatReader` for some reason so I switched to `QRCodeReader`. I'll see if I can clean it up and submit a PR.

As for your phone, what resolution images do you get from the camera? I tried setting `captureQuality` to `low` and I'm getting 1920x1080 frames.

**Comment by fbacker** [comment]
Maybe I didn't quite got the size from viewFinder to be actually from the viewfinder? Never coded for android so couldn't figure out how to place something on top and draw a 'viewfinder temp box' on top of the camera to see that it actually is in the same place.

When setting camera quality to low (Camera.constants.CaptureQuality.low) I get 
D/ISecCameraHardware( 1897): setPictureSize: 640x480

However next time I runned I keep getting crashes on RTCCameraView.java
  RCTCamera.getInstance().setActualDeviceOrientation(_actualDeviceOrientation);

Will look at it with fresh eyes tomorrow.

**Comment by tonypeng** [comment]
640x480 could be why you're getting better performance--it seems strange the lowest quality I can get from the camera is 1920x1080. I will investigate the quality setting code.

**Comment by patmisch** [comment]
@tonypeng care to share your updated fork where you're getting 60 fps on the UI to github?

**Comment by patmisch** [comment]
I've also noticed this branch causes subviews to no longer show

**Comment by tonypeng** [comment]
@patmisch I've been busy the past couple of days so I've been unable to clean up the code/investigate the accuracy issues--I expect to be able to do so soon and will submit a PR! 

As for the sub view issue, it's probably because of the viewfinder. I've worked around it using a sibling overlay view.

**Comment by fbacker** [comment]
I got hold of an Galaxy S6, notice that the viewfinder size isn't correct depending on resolution. So I've made an update to fix that.

When using sub views I've done as same as @tonypeng 

example: 

	<View style={styles.container}>
	
	  <Scanner ref="camera" onCode={this._onCode.bind(this)}
	    cameraType={this.state.cameraType}
	    torchMode={this.state.torchMode} />
	
	
	  <View style={[styles.overlay, styles.topOverlay]}>
	    <Button transparent style={styles.torchButton}
	      onPress={this._switchFlash.bind(this)} >
	      <Thumbnail source={this.torchIcon} />
	    </Button>
	    <Text style={styles.textNum}>{this.state.numOfCodes}</Text>
	  </View>
	
	
	  <View style={[styles.overlay, styles.bottomOverlay]} >
	    <Button block danger style={styles.bottomButton}
	      onPress={this._onCancel.bind(this)}>Sluta scanna</Button>
	  </View>
	
	</View>
	
	const styles = StyleSheet.create({
	  camera: {
	    flex: 1,
	  },
	  container: {
	    flex: 1,
	  },
	  overlay: {
	    position: 'absolute',
	    padding: 16,
	    right: 0,
	    left: 0,
	    alignItems: 'center',
	  },
	  topOverlay: {
	    top: 0,
	    flex: 1,
	    flexDirection: 'row',
	    justifyContent: 'space-between',
	    alignItems: 'center',
	  },
	  bottomOverlay: {
	    bottom: 0,
	    flex: 1,
	    alignItems: 'center',
	  },
	  torchButton: {
	    padding: 5,
	  },
	  textNum: {
	    fontWeight: 'bold',
	    fontSize: 24,
	    padding: 5,
	    color: 'gold',
	    backgroundColor: 'rgba(0,0,0,0)',
	  },
	  bottomButton: {
	    margin: -17,
	    padding: 0,
	  },
	
	});

My scanner contains then:

	render(){
      return (
        <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          type={this.state.cameraType}
          captureAudio={false}
          captureTarget={this.cameraTypeParsed}
          captureQuality={this.state.quality}
          style={styles.camera}


          torchMode={this.torchModeParsed}
          showViewFinder={true}
          onBarCodeRead={this.barcodeReceived.bind(this)}
          barCodeTypes={['datamatrix']}
          />
      );
    }

**Comment by kevinnguy** [comment]
@fbacker thanks for working on this feature! I've created a clean project with your branch and I'm getting poor FPS and I'm not able to scan any barcodes. These are my dependencies:

```
"dependencies": {
    "react": "15.3.1",
    "react-native": "0.33.0",
    "react-native-camera": "git+https://github.com/fbacker/react-native-camera.git#android-barcode-settypes"
  }
```

and this is my setup for `Camera`:

```
<Camera ref={(camera) => { this.camera = camera; }}
        style={styles.camera}
        aspect={this.state.camera.aspect}
        captureTarget={this.state.camera.captureTarget}
        type={this.state.camera.type}
        captureQuality={this.state.camera.captureQuality}
        captureAudio={false}
        showViewFinder={true}
        onBarCodeRead={(code) => this.props.scanBarcode(code)}
        defaultTouchToFocus={true}
        barCodeTypes={[
          'aztec',
          'codabar',
          'code128',
          'code39',
          'code39mod43',
          'code93',
          'datamatrix',
          'ean13',
          'ean8',
          'itf',
          'maxicode',
          'pdf417',
          'qr',
          'rss14',
          'rss',
          'upca',
          'upce',
          'upc'
        ]}>
      </Camera>
```

I've also created a repo for this example project if you want to check it out: https://github.com/kevinnguy/react-native-camera-example

**Comment by fbacker** [comment]
Sorry, havn't had time to try it out. Swamped at work.
Have you tried using fewer types? Thinking if it's the zxing engine

	barCodeTypes={[
	  'qr'
	]}>

**Comment by chirag04** [comment]
@fbacker Barcode support on android is already merged on master branch. Can you try that branch and iterate on that?

**Pull request closed without merging**
