### PR TITLE
Update from View.propTypes to ViewPropTypes to match RN v0.44.0

### PR DESCRIPTION
**Pull request by TBouder**
Update the ViewPropTypes to match the last revision of React Native V0.44.0

> View.propTypes to ViewPropTypes (53905a5) - @bvaughn
https://github.com/facebook/react-native/releases

### CODE REVIEW

**Comment by rt2zz** [comment]
As I recall, the peer dep was recently removed which makes me concerned to ship this change. Prematurely.

**Comment by npomfret** [comment]
I'm getting a bunch of warnings from my RN0.44 app now - I think this change will help.  I'll test it from my fork.

**Comment by npomfret** [comment]
Looks good to me. @rt2zz what are your concerns re merging this?

**Comment by rt2zz** [comment]
nothing lets do it. ViewPropTypes will not exist in older versions of react-native, but we cannot wait on that forever.

**Pull request merged**
