### PR TITLE
make fixOrientation an option

### PR DESCRIPTION
**Pull request by npomfret**
* added an option to fix orientation, which defaults to false
* when 'fixing' the orientation it now does nothing if the orientation in the exif data is already set to '1' (right way up)
* after fixing the orientation it writes the orientation value into the exif data (instead of deleting it in iOS, and leaving it unchanged in android)

How to test:

In summary I think that auto-fixing the orientation isn't required because the EXIF data is now preserved.  So I've added a property `fixOrientation` which defaults to false in this PR.  So if you don't set it (i.e. make no changes to your JS code) and take a photo at each of the 4 possible orientations I think they should come out correctly.

### CODE REVIEW

**Comment by npomfret** [comment]
I've not been able to test this on android because my devices don't set the exif data, i just get right-way-up images.

I have tested on iOS and it seems fine.  Interestingly I noticed that only 2 of the 3 rotations are applied in the iOS code (there's no 90 degree rotation) which confused me.  I still can't figure out why - does anyone know why?

Also, the rotations in the iOS code are applied differently to the android code.  The exif values are interpreted differently:

```
if (metadataOrientation == 6) {
              rotatedCGImage = [self newCGImageRotatedByAngle:cgImage angle:270];
              rotated = true;
            } else if (metadataOrientation == 3) {
              rotatedCGImage = [self newCGImageRotatedByAngle:cgImage angle:180];
              rotated = true;
            }
```

And in android its:

```
switch (exifOrientation) {
            case 1:
                return;//no rotation required
            case 2:
                bitmapMatrix.postScale(-1, 1);
                break;
            case 3:
                bitmapMatrix.postRotate(180);
                break;
            case 4:
                bitmapMatrix.postRotate(180);
                bitmapMatrix.postScale(-1, 1);
                break;
            case 5:
                bitmapMatrix.postRotate(90);
                bitmapMatrix.postScale(-1, 1);
                break;
            case 6://this is 270 degrees in iOS!?
                bitmapMatrix.postRotate(90);
                break;
            case 7:
                bitmapMatrix.postRotate(270);
                bitmapMatrix.postScale(-1, 1);
                break;
            case 8:
                bitmapMatrix.postRotate(270);
                break;
            default:
                break;
        }
```

**Comment by molerat619** [comment]
Thanks for your contribution! How can I test this? Never tried to get PR from GitHub running on my machine before. I will be happy to give you feedback for an Android 4.4 device.

**Comment by npomfret** [comment]
ok, the easiest way probably is to run with my fork.  Edit your package.json and replace the react-native-camera url with the url of my fork which is git+https://github.com/npomfret/react-native-camera.git

Then run `npm install && react-native start`.  When you're done testing remember to revert the change.

**Comment by molerat619** [comment]
I have tested your fix (up to commit 71a188d) and removed the largeHeap fix before I started actually testing. I have performed actions that would have caused a crash without the largeHeap and without your fix and this time, the app did not crash. There are no performance improvements though.

**Comment by npomfret** [comment]
@molerat619 thanks for testing, thats good news that it doesn't crash.  Have you tried taking image at all 4 camera orientations?  Did they appear correctly?

**Comment by molerat619** [comment]
Correct. Of course, upside-down is not possible, but the other 3 orientations worked no problem.

**Comment by mikaello** [comment]
I have testet this PR now, but on my phone both the current master (d54eae9ea5c41d5a1cf955cc5c7ec2f88dff81ba) and your PR seems to behave the same, all orientations seemed to appear correctly.

**Top row:** default camera on my Samsung S7
**Middle row:** current master (`└── react-native-camera@0.7.0  (git://github.com/lwansbrough/react-native-camera.git#d54eae9ea5c41d5a1cf955cc5c7ec2f88dff81ba)`)
**Bottom row:** your PR (`└── react-native-camera@0.7.0  (git+https://github.com/npomfret/react-native-camera.git#85761123799bb4f37a302009a6c7967990aec8c5)`)

**First column:** Picture taken in normal portrait
**Second column:** Phone rotated 90 degrees to the right (from normal potrait)
**Third column:** Upside down portrait
**Fourth column:** Phone rotated 90 degrees to the left (from normail portrait)

Screenshot of the grid view in the default gallery app on Samsung S7:

**Comment by rt2zz** [comment]
awesome, @npomfret is this ready?

**Comment by npomfret** [comment]
There's a conflict, and it needs a document update.  I'll sort it today.

Still a bit nervous.  Would like to get it tested on more devices.  If it is ok, then in time I think we should remove the optional 'fixRotation' altogether.

**Comment by ptomasroos** [comment]
I agree @npomfret this should not be a special prop, feels awkward

**Comment by npomfret** [comment]
I think it's premature to remove it altogether, maybe in a future release.

**Comment by Antoine-C** [comment]
Nice job @npomfret !

Is this PR ready to be merged in master ?

**Comment by npomfret** [comment]
@rt2zz would you like to merge this - i think it's ready for master.

**Comment by rt2zz** [comment]
@npomfret 👍  thank you!

**Comment by QQizi** [comment]
@npomfret I'm developping an app who require some webview with a canvas in it.

When i capture a picture with react-native-camera and send it to the webview, the image always comes out rotated in landscape. This bug doesn't happen in simulator and doesn't happen with CameraRoll.

If i use fixOrientation : true, problem does not appear.
I'm on iPhone 6 IOS 10.3.2

So i guess fixOrientation is still needed

**Comment by npomfret** [comment]
Thanks for the feedback.  Maybe some web browsers ignore the embedded metadata.  Which browser do you see the rotate image in?

**Comment by QQizi** [comment]
@npomfret I'm using the react-native Webview component, not a web browser.

**Comment by npomfret** [comment]
On what devices?

**Comment by QQizi** [comment]
@npomfret  I'm on iPhone 6 IOS 10.3.2

**Comment by skovhus** [comment]
@npomfret I've tested out #682 (0.10.0):
- you can now avoid the memory crash if not using the `fixOrientation` flag
- but the rotation is still wrong -90 for front facing camera the different Android devices I tested (Samsung Galaxy S7 / Android 7 and a Samsung Galaxy S4 Android 5)

**Comment by mikaello** [comment]
In my app the front facing camera is important, and a lot of users are using Android, so I have figured out that version 0.8.0 works, but any later version has the -90 rotation bug.

**Comment by skovhus** [comment]
0.8.0 had a auto rotation that caused memory issues on old android phones. 0.9+ made this optional using the fixOrientation flag.

**Pull request merged**
