### PR TITLE
Update compileSdkVersion to 25 and buildToolsVersion to 25.0.2

### PR DESCRIPTION
**Pull request by joshuapinter**
Best to keep these up-to-date. Doesn't affect backwards compatibility.

### CODE REVIEW

**Comment by rt2zz** [comment]
Most of the ecosystem is still 23.0.1, is there an advantage to updating?

react-native-maps is on `25.0.2` seems a reasonable update.

**Comment by rt2zz** [comment]
can you add a note to the readme, and then we will get this merged in

**Comment by joshuapinter** [comment]
@rt2zz I didn't know the ecosystem was on 23.0.1 still but for me the advantage is when adding this to new or up-to-date projects, Android Studio / Gradle complains that the Gradle Build Tools (`23.0.1`) is too low to compile and needs to be at least `25.0.0`.

We have to manually update this locally with each new team member that we onboard.

I'll add something to the README  in a second here...

**Comment by joshuapinter** [comment]
Take a look at that and let me know if that's sufficient.

**Comment by joshuapinter** [comment]
👍

**Comment by rt2zz** [comment]
also added this note: https://github.com/lwansbrough/react-native-camera/blob/master/README.md#android-build-tools-has-been-bumped-to-2502-please-update-can-be-done-via-android-cli-or-androidstudio

Thank you!

**Pull request merged**
