### PR TITLE
improve speed of barcode

### PR DESCRIPTION
**Pull request by zongwan**
long interval `onBarCodeRead` on MeiZu Phone

The below code cost a lot of time in the background.
```Java
if (RCTCamera.getInstance().getActualDeviceOrientation() == 0) {
  byte[] rotated = new byte[imageData.length];
  for (int y = 0; y < height; y++) {
    for (int x = 0; x < width; x++) {
      rotated[x * height + height - y - 1] = imageData[x + y * width];
    }
  }
  width = size.height;
  height = size.width;
  imageData = rotated;
}
```

### CODE REVIEW

**Comment by 6pm** [comment]
It is awesome. Do you tested your code on real devices?

**Comment by zongwan** [comment]
Yes, it's work fine on MeiZu Phone and Smartisan M1L.

**Comment by sibelius** [comment]
@zongwan can you provide a repo example with this?

**Comment by zongwan** [comment]
The latest version is better

**Pull request closed without merging**
