### PR TITLE
Fix scan on landscape mode

### PR DESCRIPTION
**Pull request by 6pm**

### CODE REVIEW

**Comment by alexpanov** [comment]
Can we please merge this until it starts having conflicts? @lwansbrough

**Comment by rafaelcorreiapoli** [comment]
I also need this

**Comment by 6pm** [comment]
works fine! I tested it for month. @lwansbrough please merge

**Comment by niom** [comment]
We have been using this too. What would it take to get this merged? Help needed?

**Comment by rt2zz** [comment]
additional testers and maintainers are sorely need, if anyone wants to pitch in please get in touch!

**Comment by rt2zz** [comment]
also thanks @6pm

**Comment by 6pm** [comment]
@rt2zz You are welcome!

**Comment by koswarabilly** [comment]
i am sorry in advance,
please check on passing location metadata,
it does not work

**Comment by 6pm** [comment]
@koswarabilly please describe your problem

**Pull request merged**
