### PR TITLE
android performance improvements

### PR DESCRIPTION
**Pull request by npomfret**
* removed some of the re-parsing of the output image byte array
 * removed re-saving of output file
 * moved image processing onto an async task to allow camera to be used while processing is running

### CODE REVIEW

**Comment by npomfret** [comment]
I've asked a couple of people who've complained about performance to test but no response so far.  I've tested on some pretty low spec android 4.1 and 5 devices and it seems fine so far.  The image processing step is still not as fast as I'd like it to be though.

And we're losing some of the image metadata because the android exif library doesn't understand very many tags.  Maybe I'll look into finding a replacement for that next.

**Comment by rt2zz** [comment]
This is certainly a step in the right direction, lets get it on master which should get some more eyes on it.

**Comment by molerat619** [comment]
Thanks for working on these improvements. Maybe I am testing the wrong things, but I can't see any improvements on my LG G2 Android 4.4.
I was on 0.6.0 and upgraded using `npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save` - I hope that was correct.

The problems that I am facing are the following:
- very slow transition from one scene to camera scene
- if I use interaction manager, transition is good, but camera still takes too long to load (compared to Whatsapp for example)
- after taking a picture, the transition to the next scene takes too long (starts too late)

I am sure, some issues are on my side or react-native-router-flux. I would still be very grateful if anybody could support me here. I have been testing several things for days now.

**Comment by npomfret** [comment]
I don't know what's causing this for you.  I've tested this on some very old and low powered android phones and if feels good.  Perhaps you could rule out the camera API by not loading it and see if your scene transition times are still slow.

**Pull request merged**
